version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: toiapp_postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: toiapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - toiapp_pgdata:/var/lib/postgresql/data

volumes:
  toiapp_pgdata:
